In [15]:
import pandas as pd
import numpy as np

In [16]:
data = pd.read_csv('modified_dataset3.csv')

In [17]:
data

     URL_ID                                                URL
0        37      ai in healthcare to improve patient outcomes
1        38   what if the creation is taking over the creator
2        39  what jobs will robots take from humans in the ...
3        40  will machine replace the human in the future o...
4        41                will ai replace us or work with us
..      ...                                                ...
109     146                           blockchain for payments
110     147                           the future of investing
111     148                  big data analytics in healthcare
112     149     business analytics in the healthcare industry
113     150  challenges and opportunities of big data in he...

[114 rows x 2 columns]

In [18]:
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\d jashwanth
[nltk_data]     sai\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
with open('StopWords_GenericLong.txt', 'r') as f:
    stopword_list = [word.strip() for word in f.readlines()]

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
# Remove stopwords from the 'Text' column
data['URL'] = data['URL'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stopword_list]))

# Save the modified dataset to a new file
data.to_csv('modified_wordsinlist1.csv', index=False)

In [20]:
data

     URL_ID                                           URL
0        37        ai healthcare improve patient outcomes
1        38                       creation taking creator
2        39                     jobs robots humans future
3        40             machine replace human future work
4        41                               ai replace work
..      ...                                           ...
109     146                           blockchain payments
110     147                              future investing
111     148                 big data analytics healthcare
112     149        business analytics healthcare industry
113     150  challenges opportunities big data healthcare

[114 rows x 2 columns]

In [21]:
with open('StopWords_Generic.txt', 'r') as f:
    stopword_list = [word.strip() for word in f.readlines()]

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
# Remove stopwords from the 'Text' column
data['URL'] = data['URL'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stopword_list]))

# Save the modified dataset to a new file
data.to_csv('modified_wordsinlist2.csv', index=False)

In [22]:
data

     URL_ID                                           URL
0        37        ai healthcare improve patient outcomes
1        38                       creation taking creator
2        39                     jobs robots humans future
3        40             machine replace human future work
4        41                               ai replace work
..      ...                                           ...
109     146                           blockchain payments
110     147                              future investing
111     148                 big data analytics healthcare
112     149        business analytics healthcare industry
113     150  challenges opportunities big data healthcare

[114 rows x 2 columns]

In [23]:
with open('StopWords_DatesandNumbers.txt', 'r') as f:
    stopword_list = [word.strip() for word in f.readlines()]

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
# Remove stopwords from the 'Text' column
data['URL'] = data['URL'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stopword_list]))

# Save the modified dataset to a new file
data.to_csv('modified_wordsinlist3.csv', index=False)

In [24]:
data

     URL_ID                                           URL
0        37        ai healthcare improve patient outcomes
1        38                       creation taking creator
2        39                     jobs robots humans future
3        40             machine replace human future work
4        41                               ai replace work
..      ...                                           ...
109     146                           blockchain payments
110     147                              future investing
111     148                 big data analytics healthcare
112     149        business analytics healthcare industry
113     150  challenges opportunities big data healthcare

[114 rows x 2 columns]

In [25]:
with open('StopWords_Currencies.txt', 'r') as f:
    stopword_list = [word.strip() for word in f.readlines()]

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
# Remove stopwords from the 'Text' column
data['URL'] = data['URL'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stopword_list]))

# Save the modified dataset to a new file
data.to_csv('modified_wordsinlist4.csv', index=False)

In [26]:
data

     URL_ID                                           URL
0        37        ai healthcare improve patient outcomes
1        38                       creation taking creator
2        39                     jobs robots humans future
3        40             machine replace human future work
4        41                               ai replace work
..      ...                                           ...
109     146                           blockchain payments
110     147                              future investing
111     148                 big data analytics healthcare
112     149        business analytics healthcare industry
113     150  challenges opportunities big data healthcare

[114 rows x 2 columns]

In [27]:
with open('StopWords_Geographic.txt', 'r') as f:
    stopword_list = [word.strip() for word in f.readlines()]

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
# Remove stopwords from the 'Text' column
data['URL'] = data['URL'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stopword_list]))

# Save the modified dataset to a new file
data.to_csv('modified_wordsinlist5.csv', index=False)

In [28]:
data

     URL_ID                                           URL
0        37        ai healthcare improve patient outcomes
1        38                       creation taking creator
2        39                     jobs robots humans future
3        40             machine replace human future work
4        41                               ai replace work
..      ...                                           ...
109     146                           blockchain payments
110     147                              future investing
111     148                 big data analytics healthcare
112     149        business analytics healthcare industry
113     150  challenges opportunities big data healthcare

[114 rows x 2 columns]

In [29]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to C:\Users\d jashwanth
[nltk_data]     sai\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [30]:
sid = SentimentIntensityAnalyzer()

# Perform text analysis and compute variables
def compute_sentiment_scores(URL):
    sentiment_scores = sid.polarity_scores(URL)
    positive_score = sentiment_scores['pos']
    negative_score = sentiment_scores['neg']
    return positive_score, negative_score

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
data['Positive Score'], data['Negative Score'] = zip(*data['URL'].apply(compute_sentiment_scores))

In [31]:
data

,URL_ID,URL,Positive Score,Negative Score
0,37,ai healthcare improve patient outcomes,0.420,0.0
1,38,creation taking creator,0.512,0.0
2,39,jobs robots humans future,0.000,0.0
3,40,machine replace human future work,0.000,0.0
4,41,ai replace work,0.000,0.0
...,...,...,...,...
109,146,blockchain payments,0.000,0.0
110,147,future investing,0.000,0.0
111,148,big data analytics healthcare,0.000,0.0
112,149,business analytics healthcare industry,0.000,0.0
113,150,challenges opportunities big data healthcare,0.565,0.0

In [32]:
!pip install textblob

Requirement already satisfied: textblob in c:\users\d jashwanth sai\anaconda3\lib\site-packages (0.17.1)
Requirement already satisfied: nltk>=3.1 in c:\users\d jashwanth sai\anaconda3\lib\site-packages (from textblob) (3.7)
Requirement already satisfied: regex>=2021.8.3 in c:\users\d jashwanth sai\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (2022.7.9)
Requirement already satisfied: joblib in c:\users\d jashwanth sai\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (1.1.0)
Requirement already satisfied: tqdm in c:\users\d jashwanth sai\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (4.64.1)
Requirement already satisfied: click in c:\users\d jashwanth sai\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (8.0.4)
Requirement already satisfied: colorama in c:\users\d jashwanth sai\anaconda3\lib\site-packages (from click->nltk>=3.1->textblob) (0.4.5)

WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)

In [33]:
from textblob import TextBlob

def compute_sentiment_scores(URL):
    blob = TextBlob(URL)
    polarity_score = blob.sentiment.polarity
    subjectivity_score = blob.sentiment.subjectivity
    return polarity_score, subjectivity_score

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
data['Polarity Score'], data['Subjectivity Score'] = zip(*data['URL'].apply(compute_sentiment_scores))

In [34]:
data

,URL_ID,URL,Positive Score,Negative Score,Polarity Score,Subjectivity Score
0,37,ai healthcare improve patient outcomes,0.420,0.0,0.0,0.0000
1,38,creation taking creator,0.512,0.0,0.0,0.0000
2,39,jobs robots humans future,0.000,0.0,0.0,0.1250
3,40,machine replace human future work,0.000,0.0,0.0,0.1125
4,41,ai replace work,0.000,0.0,0.0,0.0000
...,...,...,...,...,...,...
109,146,blockchain payments,0.000,0.0,0.0,0.0000
110,147,future investing,0.000,0.0,0.0,0.1250
111,148,big data analytics healthcare,0.000,0.0,0.0,0.1000
112,149,business analytics healthcare industry,0.000,0.0,0.0,0.0000
113,150,challenges opportunities big data healthcare,0.565,0.0,0.0,0.1000

In [38]:
!pip install textstat

Collecting textstat
  Downloading textstat-0.7.3-py3-none-any.whl (105 kB)
     -------------------------------------- 105.1/105.1 kB 1.5 MB/s eta 0:00:00
Collecting pyphen
  Downloading pyphen-0.14.0-py3-none-any.whl (2.0 MB)
     ---------------------------------------- 2.0/2.0 MB 2.4 MB/s eta 0:00:00
Installing collected packages: pyphen, textstat
Successfully installed pyphen-0.14.0 textstat-0.7.3

WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)

In [44]:
import nltk

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('tagsets')



# Function to calculate average number of words per sentence
def average_words_per_sentence(URL):
    sentences = nltk.sent_tokenize(URL)
    word_count = sum(len(nltk.word_tokenize(sentence)) for sentence in sentences)
    return word_count / len(sentences)

# Function to calculate readability score
def readability_score(URL):
    words = nltk.word_tokenize(URL)
    num_words = len(words)
    num_sentences = len(nltk.sent_tokenize(URL))
    num_syllables = sum(len(word) for word in words if word.lower() not in ['a', 'i']) # Approximation
    score = 206.835 - 1.015 * (num_words / num_sentences) - 84.6 * (num_syllables / num_words)
    return score

# Apply readability and average words per sentence analysis to the dataset
data['Average Words per Sentence'] = data['URL'].apply(average_words_per_sentence)
data['Readability Score'] = data['URL'].apply(readability_score)

# Save the modified dataset
data.to_csv('analyzed_dataset.csv', index=False)

[nltk_data] Downloading package punkt to C:\Users\d jashwanth
[nltk_data]     sai\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\d jashwanth sai\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package tagsets to C:\Users\d jashwanth
[nltk_data]     sai\AppData\Roaming\nltk_data...
[nltk_data]   Package tagsets is already up-to-date!

In [45]:
data

,URL_ID,URL,Positive Score,Negative Score,Polarity Score,Subjectivity Score,readability,Average Words per Sentence,Readability Score
0,37,ai healthcare improve patient outcomes,0.420,0.0,0.0,0.0000,[ai healthcare improve patient outcomes],5.0,-373.520
1,38,creation taking creator,0.512,0.0,0.0,0.0000,[creation taking creator],3.0,-388.410
2,39,jobs robots humans future,0.000,0.0,0.0,0.1250,[jobs robots humans future],4.0,-262.525
3,40,machine replace human future work,0.000,0.0,0.0,0.1125,[machine replace human future work],5.0,-288.920
4,41,ai replace work,0.000,0.0,0.0,0.0000,[ai replace work],3.0,-162.810
...,...,...,...,...,...,...,...,...,...
109,146,blockchain payments,0.000,0.0,0.0,0.0000,[blockchain payments],2.0,-556.595
110,147,future investing,0.000,0.0,0.0,0.1250,[future investing],2.0,-429.695
111,148,big data analytics healthcare,0.000,0.0,0.0,0.1000,[big data analytics healthcare],4.0,-347.125
112,149,business analytics healthcare industry,0.000,0.0,0.0,0.0000,[business analytics healthcare industry],4.0,-537.475
113,150,challenges opportunities big data healthcare,0.565,0.0,0.0,0.1000,[challenges opportunities big data healthcare],5.0,-475.040

In [50]:
import string


# Function to count the number of words in a text
def count_words(URL):
    words = URL.split()
    return len(words)

# Function to count the number of complex words in a text
def count_complex_words(URL):
    words = URL.split()
    complex_word_count = 0
    for word in words:
        word = word.strip(string.punctuation)
        if len(word) > 2 and word.isalpha() and len(set(word.lower())) > 2:
            complex_word_count += 1
    return complex_word_count

# Apply word count and complex word count analysis to the dataset
data['Word Count'] = data['URL'].apply(count_words)
data['Complex Word Count'] = data['URL'].apply(count_complex_words)

# Save the modified dataset
data.to_csv('analyzed_dataset1.csv', index=False)

In [51]:
data

,URL_ID,URL,Positive Score,Negative Score,Polarity Score,Subjectivity Score,readability,Average Words per Sentence,Readability Score,Word Count,Complex Word Count
0,37,ai healthcare improve patient outcomes,0.420,0.0,0.0,0.0000,[ai healthcare improve patient outcomes],5.0,-373.520,5,4
1,38,creation taking creator,0.512,0.0,0.0,0.0000,[creation taking creator],3.0,-388.410,3,3
2,39,jobs robots humans future,0.000,0.0,0.0,0.1250,[jobs robots humans future],4.0,-262.525,4,4
3,40,machine replace human future work,0.000,0.0,0.0,0.1125,[machine replace human future work],5.0,-288.920,5,5
4,41,ai replace work,0.000,0.0,0.0,0.0000,[ai replace work],3.0,-162.810,3,2
...,...,...,...,...,...,...,...,...,...,...,...
109,146,blockchain payments,0.000,0.0,0.0,0.0000,[blockchain payments],2.0,-556.595,2,2
110,147,future investing,0.000,0.0,0.0,0.1250,[future investing],2.0,-429.695,2,2
111,148,big data analytics healthcare,0.000,0.0,0.0,0.1000,[big data analytics healthcare],4.0,-347.125,4,4
112,149,business analytics healthcare industry,0.000,0.0,0.0,0.0000,[business analytics healthcare industry],4.0,-537.475,4,4
113,150,challenges opportunities big data healthcare,0.565,0.0,0.0,0.1000,[challenges opportunities big data healthcare],5.0,-475.040,5,5

In [52]:

# Function to count the number of syllables in a word
def count_syllables(word):
    word = word.lower()
    if len(word) <= 3:
        return 1
    count = 0
    vowels = 'aeiouy'
    if word[0] in vowels:
        count += 1
    for index in range(1, len(word)):
        if word[index] in vowels and word[index-1] not in vowels:
            count += 1
    if word.endswith('e'):
        count -= 1
    if count == 0:
        count += 1
    return count

# Function to count personal pronouns in a text
def count_personal_pronouns(URL):
    pronouns = ['i', 'me', 'my', 'mine', 'myself', 'we', 'us', 'our', 'ours', 'ourselves',
                'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself',
                'she', 'her', 'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their',
                'theirs', 'themselves']
    count = 0
    words = URL.split()
    for word in words:
        word = word.strip(string.punctuation).lower()
        if word in pronouns:
            count += 1
    return count

# Function to calculate the average word length in a text
def average_word_length(URL):
    words = URL.split()
    total_length = sum(len(word.strip(string.punctuation)) for word in words)
    return total_length / len(words)

# Apply syllable count, personal pronouns, and average word length analysis to the dataset
data['Syllable Count'] = data['URL'].apply(lambda x: sum(count_syllables(word) for word in x.split()))
data['Personal Pronouns'] = data['URL'].apply(count_personal_pronouns)
data['Average Word Length'] = data['URL'].apply(average_word_length)

# Save the modified dataset
data.to_csv('analyzed_datasetfinal.csv', index=False)

In [53]:
data

,URL_ID,URL,Positive Score,Negative Score,Polarity Score,Subjectivity Score,readability,Average Words per Sentence,Readability Score,Word Count,Complex Word Count,Syllable Count,Personal Pronouns,Average Word Length
0,37,ai healthcare improve patient outcomes,0.420,0.0,0.0,0.0000,[ai healthcare improve patient outcomes],5.0,-373.520,5,4,10,0,6.800000
1,38,creation taking creator,0.512,0.0,0.0,0.0000,[creation taking creator],3.0,-388.410,3,3,6,0,7.000000
2,39,jobs robots humans future,0.000,0.0,0.0,0.1250,[jobs robots humans future],4.0,-262.525,4,4,7,0,5.500000
3,40,machine replace human future work,0.000,0.0,0.0,0.1125,[machine replace human future work],5.0,-288.920,5,5,9,0,5.800000
4,41,ai replace work,0.000,0.0,0.0,0.0000,[ai replace work],3.0,-162.810,3,2,4,0,4.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,146,blockchain payments,0.000,0.0,0.0,0.0000,[blockchain payments],2.0,-556.595,2,2,4,0,9.000000
110,147,future investing,0.000,0.0,0.0,0.1250,[future investing],2.0,-429.695,2,2,5,0,7.500000
111,148,big data analytics healthcare,0.000,0.0,0.0,0.1000,[big data analytics healthcare],4.0,-347.125,4,4,9,0,6.500000
112,149,business analytics healthcare industry,0.000,0.0,0.0,0.0000,[business analytics healthcare industry],4.0,-537.475,4,4,12,0,8.750000
113,150,challenges opportunities big data healthcare,0.565,0.0,0.0,0.1000,[challenges opportunities big data healthcare],5.0,-475.040,5,5,13,0,8.000000

In [55]:
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('tagsets')

# Function to calculate the Gunning Fog Index
def calculate_fog_index(URL):
    sentences = nltk.sent_tokenize(URL)
    total_words = 0
    total_complex_words = 0
    for sentence in sentences:
        words = nltk.word_tokenize(sentence)
        total_words += len(words)
        for word in words:
            word = word.strip(string.punctuation)
            if len(word) > 2 and word.isalpha() and len(set(word.lower())) > 2:
                total_complex_words += 1
    if total_words == 0:
        return 0
    fog_index = 0.4 * ((total_words / len(sentences)) + (100 * (total_complex_words / total_words)))
    return fog_index

# Apply FOG index analysis to the dataset
data['FOG Index'] = data['URL'].apply(calculate_fog_index)

# Save the modified dataset
data.to_csv('analyzed_datasetfinal1.csv', index=False)

[nltk_data] Downloading package punkt to C:\Users\d jashwanth
[nltk_data]     sai\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\d jashwanth sai\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package tagsets to C:\Users\d jashwanth
[nltk_data]     sai\AppData\Roaming\nltk_data...
[nltk_data]   Package tagsets is already up-to-date!

In [56]:
data

,URL_ID,URL,Positive Score,Negative Score,Polarity Score,Subjectivity Score,readability,Average Words per Sentence,Readability Score,Word Count,Complex Word Count,Syllable Count,Personal Pronouns,Average Word Length,FOG Index
0,37,ai healthcare improve patient outcomes,0.420,0.0,0.0,0.0000,[ai healthcare improve patient outcomes],5.0,-373.520,5,4,10,0,6.800000,34.000000
1,38,creation taking creator,0.512,0.0,0.0,0.0000,[creation taking creator],3.0,-388.410,3,3,6,0,7.000000,41.200000
2,39,jobs robots humans future,0.000,0.0,0.0,0.1250,[jobs robots humans future],4.0,-262.525,4,4,7,0,5.500000,41.600000
3,40,machine replace human future work,0.000,0.0,0.0,0.1125,[machine replace human future work],5.0,-288.920,5,5,9,0,5.800000,42.000000
4,41,ai replace work,0.000,0.0,0.0,0.0000,[ai replace work],3.0,-162.810,3,2,4,0,4.333333,27.866667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,146,blockchain payments,0.000,0.0,0.0,0.0000,[blockchain payments],2.0,-556.595,2,2,4,0,9.000000,40.800000
110,147,future investing,0.000,0.0,0.0,0.1250,[future investing],2.0,-429.695,2,2,5,0,7.500000,40.800000
111,148,big data analytics healthcare,0.000,0.0,0.0,0.1000,[big data analytics healthcare],4.0,-347.125,4,4,9,0,6.500000,41.600000
112,149,business analytics healthcare industry,0.000,0.0,0.0,0.0000,[business analytics healthcare industry],4.0,-537.475,4,4,12,0,8.750000,41.600000
113,150,challenges opportunities big data healthcare,0.565,0.0,0.0,0.1000,[challenges opportunities big data healthcare],5.0,-475.040,5,5,13,0,8.000000,42.000000