In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('modified_dataset3.csv')

In [3]:
data

     URL_ID                                                URL
0        37      ai in healthcare to improve patient outcomes
1        38   what if the creation is taking over the creator
2        39  what jobs will robots take from humans in the ...
3        40  will machine replace the human in the future o...
4        41                will ai replace us or work with us
..      ...                                                ...
109     146                           blockchain for payments
110     147                           the future of investing
111     148                  big data analytics in healthcare
112     149     business analytics in the healthcare industry
113     150  challenges and opportunities of big data in he...

[114 rows x 2 columns]

In [12]:
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\d jashwanth
[nltk_data]     sai\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [14]:
with open('StopWords_GenericLong.txt', 'r') as f:
    stopword_list = [word.strip() for word in f.readlines()]

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
# Remove stopwords from the 'Text' column
data['URL'] = data['URL'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stopword_list]))

# Save the modified dataset to a new file
data.to_csv('modified_wordsinlist1.csv', index=False)

In [16]:
with open('StopWords_Generic.txt', 'r') as f:
    stopword_list = [word.strip() for word in f.readlines()]

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
# Remove stopwords from the 'Text' column
data['URL'] = data['URL'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stopword_list]))

# Save the modified dataset to a new file
data.to_csv('modified_wordsinlist2.csv', index=False)

In [17]:
with open('StopWords_DatesandNumbers.txt', 'r') as f:
    stopword_list = [word.strip() for word in f.readlines()]

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
# Remove stopwords from the 'Text' column
data['URL'] = data['URL'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stopword_list]))

# Save the modified dataset to a new file
data.to_csv('modified_wordsinlist3.csv', index=False)

In [18]:
with open('StopWords_Currencies.txt', 'r') as f:
    stopword_list = [word.strip() for word in f.readlines()]

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
# Remove stopwords from the 'Text' column
data['URL'] = data['URL'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stopword_list]))

# Save the modified dataset to a new file
data.to_csv('modified_wordsinlist4.csv', index=False)

In [19]:
with open('StopWords_Geographic.txt', 'r') as f:
    stopword_list = [word.strip() for word in f.readlines()]

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
# Remove stopwords from the 'Text' column
data['URL'] = data['URL'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stopword_list]))

# Save the modified dataset to a new file
data.to_csv('modified_wordsinlist5.csv', index=False)

In [20]:
data

,URL_ID,URL,Positive Score,Negative Score
0,37,ai healthcare improve patient outcomes,0.326,0.0
1,38,creation taking creator,0.208,0.0
2,39,jobs robots humans future,0.000,0.0
3,40,machine replace human future work,0.000,0.0
4,41,ai replace work,0.000,0.0
...,...,...,...,...
109,146,blockchain payments,0.000,0.0
110,147,future investing,0.000,0.0
111,148,big data analytics healthcare,0.000,0.0
112,149,business analytics healthcare industry,0.000,0.0
113,150,challenges opportunities big data healthcare,0.394,0.0

In [21]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to C:\Users\d jashwanth
[nltk_data]     sai\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [27]:
sid = SentimentIntensityAnalyzer()

# Perform text analysis and compute variables
def compute_sentiment_scores(URL):
    sentiment_scores = sid.polarity_scores(URL)
    positive_score = sentiment_scores['pos']
    negative_score = sentiment_scores['neg']
    return positive_score, negative_score

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
data['Positive Score'], data['Negative Score'] = zip(*data['URL'].apply(compute_sentiment_scores))

In [28]:
data

,URL_ID,URL,Positive Score,Negative Score,Polarity Score,Subjectivity Score
0,37,ai healthcare improve patient outcomes,0.420,0.0,0.0,0.0000
1,38,creation taking creator,0.512,0.0,0.0,0.0000
2,39,jobs robots humans future,0.000,0.0,0.0,0.1250
3,40,machine replace human future work,0.000,0.0,0.0,0.1125
4,41,ai replace work,0.000,0.0,0.0,0.0000
...,...,...,...,...,...,...
109,146,blockchain payments,0.000,0.0,0.0,0.0000
110,147,future investing,0.000,0.0,0.0,0.1250
111,148,big data analytics healthcare,0.000,0.0,0.0,0.1000
112,149,business analytics healthcare industry,0.000,0.0,0.0,0.0000
113,150,challenges opportunities big data healthcare,0.565,0.0,0.0,0.1000

In [24]:
!pip install textblob

Collecting textblob
  Downloading textblob-0.17.1-py2.py3-none-any.whl (636 kB)
     -------------------------------------- 636.8/636.8 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: nltk>=3.1 in c:\users\d jashwanth sai\anaconda3\lib\site-packages (from textblob) (3.7)
Requirement already satisfied: regex>=2021.8.3 in c:\users\d jashwanth sai\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (2022.7.9)
Requirement already satisfied: tqdm in c:\users\d jashwanth sai\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (4.64.1)
Requirement already satisfied: click in c:\users\d jashwanth sai\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (8.0.4)
Requirement already satisfied: joblib in c:\users\d jashwanth sai\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (1.1.0)
Requirement already satisfied: colorama in c:\users\d jashwanth sai\anaconda3\lib\site-packages (from click->nltk>=3.1->textblob) (0.4.5)
Installing collected packages: textblob
Successfully installed textblob-0.17.1

WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\d jashwanth sai\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\d jashwanth sai\anaconda3\lib\site-packages)

In [25]:
from textblob import TextBlob

def compute_sentiment_scores(URL):
    blob = TextBlob(URL)
    polarity_score = blob.sentiment.polarity
    subjectivity_score = blob.sentiment.subjectivity
    return polarity_score, subjectivity_score

# Assuming you have a dataset stored in a pandas DataFrame named 'df' with a column 'Text'
data['Polarity Score'], data['Subjectivity Score'] = zip(*data['URL'].apply(compute_sentiment_scores))

In [26]:
data

,URL_ID,URL,Positive Score,Negative Score,Polarity Score,Subjectivity Score
0,37,ai healthcare improve patient outcomes,0.420,0.0,0.0,0.0000
1,38,creation taking creator,0.512,0.0,0.0,0.0000
2,39,jobs robots humans future,0.000,0.0,0.0,0.1250
3,40,machine replace human future work,0.000,0.0,0.0,0.1125
4,41,ai replace work,0.000,0.0,0.0,0.0000
...,...,...,...,...,...,...
109,146,blockchain payments,0.000,0.0,0.0,0.0000
110,147,future investing,0.000,0.0,0.0,0.1250
111,148,big data analytics healthcare,0.000,0.0,0.0,0.1000
112,149,business analytics healthcare industry,0.000,0.0,0.0,0.0000
113,150,challenges opportunities big data healthcare,0.565,0.0,0.0,0.1000